name: 'testing-conda-environment'
description: 'Test a conda environment of a specific python version against all beamlines'
inputs:
  conda_env_url:
    description: 'URL to download the conda-packd environment, e.g: https://zenodo.org/records/14862443/files/2025-1.0-py311-tiled.tar.gz'
    required: true
  conda_env_md5:
    description: 'MD5 checksum of the conda environment'
    required: true
  org:
    required: true
    description: 'beamline github org'
  repo:
    required: true
    description: 'beamline ipython profile github repository name'
  branch:
    required: true
    description: 'beamline ipython profile git branch name'
  beamline-acronym:
    required: true
    description: 'beamline tla'
runs:
  using: 'composite'

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cloning Remote Repositories
      env:
        REPO_URL: "https://github.com/${{ inputs.org }}/${{ inputs.repo }}"
      shell: bash -leo pipefail {0}
      run: |
        # mkdir -p -v "$HOME/${{ inputs.repo }}"
        git clone -b ${{ inputs.branch }} "${REPO_URL}" "$HOME/${{ inputs.repo }}"

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Beamline Specific Configurations
      env:
        ACTION_PATH: ${{ github.action_path }}
      shell: bash -leo pipefail {0}
      run: python3 ${ACTION_PATH}/special_config.py -b "${{ inputs.beamline_acronym }}"

    - name: Setting up Blackhole IOC
      shell: bash -leo pipefail {0}
      run: |
        python3 -m pip install -U caproto
        echo "\n" | python3 -m caproto.ioc_examples.pathological.spoof_beamline &
        trap 'kill -SIGINT %1; echo exiting...' EXIT
        sudo ln -svf caproto-repeater "/bin/caRepeater"

    # - name: Checking Blackhole IOC PV's
    #   run: |
    #     sudo pip install supervisor
    #     chmod +x ${ACTION_PATH}/supervisor/start_supervisor.sh
    #     ${ACTION_PATH}/supervisor/start_supervisor.sh status
    #   env:
    #     ACTION_PATH: ${{ github.action_path }}

    - name: Create a conda env from Zenodo
      shell: bash -leo pipefail {0}
      run: |
        url="${{ inputs.conda_env_url }}?download=1"
        wget --progress=dot:giga ${url} -O env.tar.gz
        status=$?
        if [ $status -gt 0 ]; then
            echo "Cannot download from ${url}. Exit code: ${status}"
            exit $status
        fi
        echo "${{ inputs.conda_env_md5 }} env.tar.gz" > checksum.txt
        md5sum --check checksum.txt
        mkdir -p $HOME/env
        echo "Unarchiving the tarball..."
        tar -xf env.tar.gz -C $HOME/env
        conda activate $HOME/env
        conda-unpack

    - name: Configuring defaults (pyOlog, databroker, and kafka)
      env:
        BEAMLINE_ACRONYM: ${{ inputs.beamline_acronym | lower }}
      shell: bash -leo pipefail {0}
      run: |
        echo "pyOlog config:"
        wget https://raw.githubusercontent.com/NSLS-II/profile-collection-ci/master/configs/pyOlog.conf -O $HOME/.pyOlog.conf
        cat $HOME/.pyOlog.conf

        echo "Classic databroker v0/v1 config:"
        databroker_conf_dir="$HOME/.config/databroker"
        beamline_acronym="${BEAMLINE_ACRONYM}"
        databroker_bl_conf="${beamline_acronym}.yml"
        mkdir -v -p ${databroker_conf_dir}
        wget https://raw.githubusercontent.com/NSLS-II/profile-collection-ci/master/configs/databroker.yml -O ${databroker_conf_dir}/_legacy_config.yml
        cp -v ${databroker_conf_dir}/_legacy_config.yml ${databroker_conf_dir}/${databroker_bl_conf}
        cat ${databroker_conf_dir}/_legacy_config.yml
        cat ${databroker_conf_dir}/${databroker_bl_conf}

        echo "Tiled profile config:"
        tiled_profiles_dir="$HOME/.config/tiled/profiles/"
        mkdir -v -p "${tiled_profiles_dir}"
        sed 's/^  //' << EOF > "${tiled_profiles_dir}/profiles.yml"
        ${beamline_acronym:-local}:
          direct:
            authentication:
              allow_anonymous_access: true
            trees:
            - tree: databroker.mongo_normalized:Tree.from_uri
              path: /
              args:
                uri: mongodb://localhost:27017/metadatastore-local
                asset_registry_uri: mongodb://localhost:27017/asset-registry-local
        EOF
          cat ${tiled_profiles_dir}/profiles.yml

          echo "Kafka config:"
          sed 's/^  //' << EOF > kafka.yml
          ---
            abort_run_on_kafka_exception: false
            bootstrap_servers:
              - localhost:9092
            runengine_producer_config:
              security.protocol: PLAINTEXT
        EOF

          echo "SUDO: Placing kafka config in /etc/bluesky"
          sudo mkdir -v -p /etc/bluesky/
          sudo mv -v kafka.yml /etc/bluesky/kafka.yml
          cat /etc/bluesky/kafka.yml

    - name: Configuring Redis
      uses: supercharge/redis-github-action@1.8.0
      with:
        redis-version: latest

    - name: Configuring Mongo
      uses: supercharge/mongodb-github-action@1.11.0
      with:
        mongodb-version: '4.4'

    - name: Performing Beamline Actions
      env:
        BEAMLINE_ACRONYM: ${{ inputs.beamline_acronym }}
      shell: bash -leo pipefail {0}
      run: |
        echo "Performing beamline-specific tasks..."
        cfg_dir="/nsls2/data/$BEAMLINE_ACRONYM/shared/config"
        if [[ ! -d "$cfg_dir" ]]; then
          sudo mkdir -v -p "$cfg_dir" ||
          (
            echo "Error: Couldn't create dir: $cfg_dir"
            exit 1
          )
        fi

    - name: Start Tiled Server
      shell: bash -leo pipefail {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate $HOME/env

        for tiled_profile_name in nsls2 ${{ inputs.beamline_acronym }}; do
          tiled profile create --name $tiled_profile_name http://127.0.0.1:8000
        done
        export TILED_API_KEY=secret
        nohup tiled serve catalog --temp --api-key=$TILED_API_KEY &
        sleep 10

    - name: Activate IPython Profile and test the code
      shell: bash -leo pipefail {0}
      run: |
        eval "$(conda shell.bash hook)"
        conda activate $HOME/env

        cd "$HOME/${{ inputs.repo }}"

        # Start Xvfb
        # (from https://developercommunity.visualstudio.com/content/problem/336288/headless-testing-using-xvfb-on-hosted-ubuntu-1604.html)
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
        export DISPLAY=:99
        # This is what IPython does internally to load the startup files:
        command="
        import os
        import glob
        ip = get_ipython()
        startup_files = sorted(glob.glob(os.path.join(os.getcwd(), 'startup/*.py')))
        if os.path.isfile('.ci/drop-in.py'):
            startup_files.append('.ci/drop-in.py')
        if not startup_files:
            raise SystemExit(f'Cannot find any startup files in {os.getcwd()}')
        for f in startup_files:
            if not os.path.isfile(f):
                raise FileNotFoundError(f'File {f} cannot be found.')
            print(f'Executing {f} in CI')
            ip.parent._exec_file(f)"
        env | grep EPICS
        ipython --profile=test -c "$command"
