name: 'Stop Blackhole IOC'
description: 'Stops the blackhole IOC'
runs:
  using: 'composite'
  steps:
    - run: |
          if [ -n "${BLACKHOLE_IOC_PID:-}" ]; then
              kill -SIGINT "${BLACKHOLE_IOC_PID}" 2>/dev/null || true
          fi
      shell: bash
      