name: 'Start Tiled server and create profiles'
description: 'Starts the Tiled server and creates profiles'
runs:
  using: 'composite'
  steps:
  # I feel like perhaps these services could be seperated out for one each?
    - run: |
        cp -v "$GITHUB_WORKSPACE/configs/pyOlog.conf" "$HOME/.pyOlog.conf"

        databroker_conf_dir="$HOME/.config/databroker"
        mkdir -v -p ${databroker_conf_dir}
        cp -v "$GITHUB_WORKSPACE/configs/databroker.yml" "${databroker_conf_dir}/_legacy_config.yml"
        cp -v ${databroker_conf_dir}/_legacy_config.yml ${databroker_conf_dir}/${BEAMLINE_ACRONYM}.yml

        tiled_profiles_dir="$HOME/.config/tiled/profiles/"
        mkdir -v -p "${tiled_profiles_dir}"
        cat << EOF > ${tiled_profiles_dir}/profiles.yml
        ${ENDSTATION_ACRONYM}:
          direct:
            authentication:
              allow_anonymous_access: true
            trees:
            - tree: databroker.mongo_normalized:Tree.from_uri
              path: /
              args:
                uri: mongodb://localhost:27017/metadatastore-local
                asset_registry_uri: mongodb://localhost:27017/asset-registry-local
        EOF

        sudo mkdir -v -p /etc/bluesky/
        cat << EOF | sudo tee /etc/bluesky/kafka.yml
        ---
          abort_run_on_kafka_exception: false
          bootstrap_servers:
            - 127.0.0.1:9092
          runengine_producer_config:
            security.protocol: PLAINTEXT
        EOF

      shell: bash